# Generated by Django 4.2.7 on 2023-12-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email_address')),
                ('welcomeCode', models.CharField(max_length=50, null=True, unique=True, verbose_name='Код приглашения')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
