# Generated by Django 4.2.7 on 2023-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_customuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
