# Generated by Django 4.2.7 on 2023-12-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
