# Generated by Django 4.2.7 on 2023-12-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('welcomeCode', models.CharField(max_length=50, null=True, verbose_name='Код приглашения')),
            ],
        ),
    ]
