# Generated by Django 4.2.7 on 2023-12-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('text', models.TextField(max_length=1000, null=True, verbose_name='Содержание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': '',
                'ordering': ['title'],
                'managed': True,
            },
        ),
    ]
