# Generated by Django 4.2.7 on 2023-12-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('theme', models.BooleanField(default=False, verbose_name='Тёмная тема')),
                ('filmed_at', models.DateTimeField(verbose_name='Дата съёмки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='ID пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=None, verbose_name='Файл')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранное?')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gallery', verbose_name='ID галереи')),
            ],
        ),
    ]
